version: "3"
services:
  postgres:
    container_name: nest-postgres
    image: postgres:13.4
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - '5432'
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: starter-redis
    user: root
    restart: always
    expose:
      - '6379'
    ports:
      - "6379:6379"
    volumes:
      - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/data/redis/data:/var/lib/redis
      - ./docker/data/redis/dumps:/usr/local/var/db/redis/

  postgres-backups:
    container_name: nest-postgres-backups
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./docker/db-backup:/backups
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=nest-postgres
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

volumes:
  db:
